{{- if .Values.config.agentKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "warpstream-agent.secretName" . }}
  labels:
    {{- include "warpstream-agent.labels" . | nindent 4 }}
data:
  agentKey: {{  required "A valid config.agentKey is required" .Values.config.agentKey |  b64enc }}
type: Opaque
# apiKey is an deprecated alias for agentKey.
{{- else if .Values.config.apiKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "warpstream-agent.secretName" . }}
  labels:
    {{- include "warpstream-agent.labels" . | nindent 4 }}
data:
  apikey: {{  required "A valid config.apiKey is required" .Values.config.apiKey |  b64enc }}
type: Opaque
{{- end }}
